#ifndef __IP_APP_USER_H__
#define __IP_APP_USER_H__

enum {
    IP_APP_CMD_MIN,
    IP_APP_GET_LOCAL_IP,
    IP_APP_SET_LOCAL_IP,
    IP_APP_GET_LOCAL_NETMASK,
    IP_APP_SET_LOCAL_NETMASK,
    IP_APP_GET_LOCAL_GATEWAY,
    IP_APP_SET_LOCAL_GATEWAY,
    IP_APP_GET_LOCAL_MAC,
    IP_APP_CMD_MAX,
};

#endif
